name: "CI"
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install requirements
        run: npm install

      - name: Build
        run: npm run build-all
        timeout-minutes: 1

      - name: Build dist
        run: npm run build-dist
        timeout-minutes: 1

      - name: Run tests
        run: npm run test
        timeout-minutes: 5

      - name: Check Exit Codes
        run: |
          if [ ${{ job.status }} == "success" ]; then
            echo "All processes exited with exit code 0."
          else
            echo "One or more processes did not exit with exit code 0."
          fi
  notify:
    runs-on: ubuntu-latest
    needs: build
    if: failure()

    steps:
      - name: Send Slack Notification on failure
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: |
            The workflow ${{ github.workflow }} has failed.
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
